######################################################################
# CENTRAL CONFIGURATION FILE
#
# Org Settings' css selectors
#
######################################################################

authorizations: 'article.main-content > ul:nth-of-type(1) > li:nth-of-type(3) > a.grid-entry-content.btn'
continue_danger: 'a.btn.btn-lg.btn-danger'
continue_primary: 'a.btn.btn-lg.btn-primary'
error_message: 'h4.message'
permissions_links: 'ul.navigation-list.vertical > li.navigation.big > a.navigation-link'
permissions_options: 'li.entry.no-image'
settings_dropdown_options: 'ul.dropdown-menu.header.on-right.fade.bottom.in > li > a'
update_button: 'button.btn.btn-success.btn-lg'

##################################
#
# Approval Chains
#
##################################

add_approval_chain: 'ul.navbar > li.navbar-entry > a'
approval_chain_approver_options: 'div.panel.approval-chain.full > div.selectable-grid > ul.entries > li.entry.source'
approval_chain_delete: 'a[data-vh-id="approval-chain-delete"]'
approval_chain_edit: 'a[data-original-title="Edit Approval Chain"]'
approval_chain_link: 'div.entry.vertically-centered > div.entry-inline-source.expand > a[data-action-handler="approval-chain"]'
approval_chain_name_field: 'input[data-vh-id="name"]'
approval_chain_remove_default: 'a.btn.entry-action.btn-success'
approval_chain_save_button: 'a.btn.btn-lg.btn-success'
approval_chain_set_default: 'a.btn.entry-action.btn-secondary'
approval_chains_list: 'div[data-vh-id="approval-chain"]'
approval_chains_option: 'article.main-content > ul:nth-of-type(2) > li:nth-of-type(5) > a.grid-entry-content.btn'
approval_chains_update_button: 'a.btn.btn-lg.btn-success'
warning_message: 'li[data-entry-id="approval-chain-readonly"]'

##################################
#
# Members
#
##################################

member_edit_role: 'a[data-vh-id="change-role"]'
member_delete: 'a[data-vh-id="delete-member"]'
members_option: 'article.main-content > ul:nth-of-type(1) > li:nth-of-type(4) > a.grid-entry-content.btn'
members_list_items: 'div[data-vh-id="member"]'
members_role_select: 'a.select2-choice.select2-default'
role_dropdown_options: 'div.select2-drop > ul > li > div > span'

##################################
#
# Publishing Campaigns
#
##################################

add_publishing_campaign: 'ul.navbar > li.navbar-entry > a'
always_campaign: 'organization_campaign_tracking'
campaign_item: 'div[data-vh-id="publishing-campaign"]'
campaigns: 'article.main-content > ul:nth-of-type(2) > li:nth-of-type(4) > a.grid-entry-content.btn'
continue: 'a[data-vh-id="with-callback"]'
name_publishing_campaign: 'input[data-vh-id="name"]'
organization_general: 'article.main-content > ul:nth-of-type(1) > li:nth-of-type(1) > a.grid-entry-content.btn'
save_campaign: '[name="button"]'
tracking_google_analytics: 'ul.entries > li:first-child'
update: '[name="button"]'
delete_campaign: 'div[data-publishing-campaign-id="###"] a[data-vh-id="publishing-campaign-delete"]'
