######################################################################
# CENTRAL CONFIGURATION FILE
#
# Personal Settings' css selectors
#
######################################################################

create_template: 'a.navbar-link.primary'
facebook: 'article.main-content > ul:nth-of-type(2) > li:nth-of-type(4) > a.grid-entry-content.btn'
facebook_search_input: 'input[data-vh-id="new-pages-query"]'
personal_settings: 'ul.dropdown-menu.header.on-right.fade.bottom.in > li:nth-of-type(1) > a'
settings: 'nav.navbar.main > div:nth-of-type(3) > a.navbar-action.with-icon'
shorten_button: 'div[data-service-name="###"] a[data-original-title="Set as default"]'
template_continue_delete: 'a[data-action-id="action-2"]'
template_delete: 'a[data-vh-id="delete-template"]'
template_dropdown: "a[class='select2-choice select2-default']"
template_dropdown_item: "li[class='select2-results-dept-0 select2-result select2-result-selectable select2-highlighted'] [class='select2-result-label']"
template_item: 'div[data-vh-id="publishing-template"]'
template_message: 'textarea[data-vh-id="message"]'
template_name: 'input[data-vh-id="name"]'
template_save: 'a[data-action="save"]'
templates: 'article.main-content > ul:nth-of-type(2) > li:nth-of-type(3) > a.grid-entry-content.btn'
url_shortening: 'article.main-content > ul:nth-of-type(2) > li:nth-of-type(2) > a.grid-entry-content.btn'
use_publishing_template: 'li[data-vh-id="template"] a[class="option-link"]'
