######################################################################
# CENTRAL CONFIGURATION FILE
#
# source page infomration
#
######################################################################

add_source_button: 'a[data-vh-id="source-add"]'
add_source_public: 'a[data-vh-id="source-add-direct"]'
add_source_green_button: 'button[class="btn btn-success btn-lg left-spaced-2"]'
add_a_new_source: 'a[href="https://staging.viralheat.com/sources/connect/pinterest"]'
pinterest_account: 'a[href="https://pinterest.com/autoqa0079"]'
continue_danger_button: 'a.btn.btn-lg.btn-danger'
create_button: 'button.btn.btn-lg.btn-success'
delete_account: 'a[data-vh-id="source-delete"]'
delete_account_confirm: 'a[data-vh-id="with-callback"]'
disabled_account: 'i[data-vh-id="invalid"]'
facebook_account: 'ul[data-vh-id="platforms"] li[data-platform="facebook"] a[data-vh-id="platform-trigger"]'
fb_accept_button: 'div[id="login_button_inline"] label[id="loginbutton"]'
fb_confim_acceptance: 'button[name="__CONFIRM__"]'
foursquare_account: 'ul[data-vh-id="platforms"] li[data-platform="foursquare"] a[data-vh-id="platform-trigger"]'
foursquare_logIn_button: 'input[id="loginFormButton"]'
google_SignIn_button: 'input[id="signIn"]'
google_accept_button: 'button[id="submit_approve_access"]'
google_account: 'ul[data-vh-id="platforms"] li[data-platform="google_plus"] a[data-vh-id="platform-trigger"]'
google_userNext_button: 'input[id="next"]'
instagram_accept_button: 'ul[class="actions"] input[value="Authorize"]'
instagram_account: 'ul[data-vh-id="platforms"] li[data-platform="instagram"] a[data-vh-id="platform-trigger"]'
instagram_logIn_button: 'input[type="submit"]'
more_account_options: 'a[class="menu-trigger entry-action"]'
no_sources_message: 'div[class="flex-element"] div[data-vh-id="empty"] i[class="fa fa-cloud"] h3[class="message"]'
publicOrg_add_source: 'div[class="box align-right"] button[data-vh-id="submit"] i[class="fa fa-plus"]'
#add_source_button: 'div[class="box align-right"] button[data-vh-id="submit"]'
reauthorize_account: 'data-vh-id="sources-connect"'
select_newSourceType_facebook: 'li[data-searchable-label="Facebook"]'
select_newSourceType_foursquare: 'li[data-searchable-label="Foursquare"]'
select_newSourceType_google: 'li[data-searchable-label="Google+"]'
select_newSourceType_instagram: 'li[data-searchable-label="Instagram"]'
select_newSourceType_topic_profile: 'li[data-searchable-label="Topic Profile"]'
select_newSourceType_tumblr: 'li[data-searchable-label="Tumblr"]'
select_newSourceType_twitter: 'li[data-searchable-label="Twitter"]'
select_newSourceType_wordpress: 'li[data-searchable-label="WordPress"]'
select_newSourceType_pinterest: 'li[data-searchable-label="Pinterest"]'
source_delete_link: 'a[data-vh-id="source-delete"]'
source_dropdown_list: 'a[data-toggle="vh-dropdown"]'
sources: 'li[data-vh-id="source"]'
sources_page: 'a[class="breadcrumb-link"]'
topic_profile_name: 'input[name="alert[profile_name]"]'
topic_profile_term: 'div#s2id_alert_or_query > ul > li > input'
topic_profile_term_delete: 'div#s2id_alert_or_query > ul > li > a.select2-search-choice-close'
tumblr_accept_button: 'button[name="allow"]'
tumblr_account: 'ul[data-vh-id="platforms"] li[data-platform="tumblr"] a[data-vh-id="platform-trigger"]'
tumblr_logIn_button: 'button[id="signup_forms_submit"]'
twitter_account: 'ul[data-vh-id="platforms"] li[data-platform="twitter"] a[data-vh-id="platform-trigger"]'
wordpress_accept_button: 'button[id="approve"]'
wordpress_account: 'ul[data-vh-id="platforms"] li[data-platform="wordpress"] a[data-vh-id="platform-trigger"]'
wordpress_logIn_button: 'button[type="submit"]'
pinterest_accept_button: 'button[type="submit"]'
pinterest_account: 'ul[data-vh-id="platforms"] li[data-platform="pinterest"] a[data-vh-id="platform-trigger"]'
pinterest_logIn_button: 'button[type="submit"]'
pinterest_authorize_button: 'button[type="submit"]'
pinterest_logIn_button3: 'button[class="Button LoginButton Module NavigateButton btn hasText loginButtonNew signupLoginButton rounded"]'
pinterest_logIn_button2: 'div[class="signupButton"]'
